version: '3.8'
services:
  mysqlbd:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-tpfoyer:
    depends_on:
      - mysqlbd
    image: koussaykouki/tp-foyer:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqlbd:3306/db?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : "",
      "spring.jpa.show-sql" : "true",
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
